name: Build React Native App w EAS
on:
  push:
    branches:
      - devops/build-dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Install expo-cli
        run: npm install -g eas-cli
      - name: Build app
        env:
          EAS_USERNAME: ${{ secrets.EAS_USERNAME }}
          EAS_PASSWORD: ${{ secrets.EAS_PASSWORD }}
        run: eas build -p android && eas build -p ios && eas build -p web
